CREATE DATABASE IF NOT EXISTS FLAPPY_BIRD_GAME;

USE FLAPPY_BIRD_GAME;

-- Users table to store unique_id and name
CREATE TABLE IF NOT EXISTS USERS (
    UNIQUE_ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

-- Scores table to store the user and their score
CREATE TABLE IF NOT EXISTS SCORES (
    UNIQUE_ID INT,
    NAME VARCHAR(50),
    SCORE INT,
    FOREIGN KEY (UNIQUE_ID) REFERENCES USERS(UNIQUE_ID)
);
desc USERS;
